project:
  type: website
  output-dir: docs

website:
  title: "SDV Posts"
  sidebar:
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Topics"
        contents:
          - text: "Getting Started"
            href: getting-started/index.qmd
          - text: "Data Generation"
            href: data-generation/index.qmd
          - text: "Privacy & Security"
            href: privacy-security/index.qmd
          - section: "Evaluation"
            href: evaluation/index.qmd
            contents:
              "evaluation/*.qmd"

collections:
  getting-started:
    title: "Getting Started with SDV"
    categories: true
    sort: "date desc"

  data-generation:
    title: "Synthetic Data Generation"
    categories: true
    sort: "date desc"

  privacy-security:
    title: "Privacy & Security"
    categories: true
    sort: "date desc"

  evaluation:
    title: "Evaluating Synthetic Data"
    categories: true
    sort: "date desc"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
