name: Quarto Docs Generation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install Dependencies
      run: |
        sudo apt-get install graphviz
        uv sync --all-extras --dev
    - name: Render Quarto Docs
      run: |
        quarto render

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: docs

